ecu:
  APS_ECU_IP: '192.168.0.42'
  APS_ECU_PORT: 8050
  APS_ECU_UPDATE_INTERVAL: 15
  APS_ECU_STOP_AT_NIGHT: True
  APS_ECU_POSITION_LAT: 52.5162
  APS_ECU_POSITION_LNG: 13.3777
  APS_ECU_TIMEZONE: 'Europe/Berlin'

mqtt:
  MQTT_BROKER_HOST: '192.168.0.2'
  MQTT_BROKER_PORT: 1883
  MQTT_BROKER_USER: ''
  MQTT_BROKER_PASSWD: ''
  MQTT_BROKER_SECURED_CONNECTION: False
  MQTT_BROKER_CACERTS_PATH: ''
  MQTT_CLIENT_ID: 'APsystemsEZ1mqtt'
  MQTT_TOPIC_PREFIX: 'aps/' # not used if HomA is enabled

  HOMA_ENABLED: True
  HOMA_SYSTEMID: '' # use inverter id if empty
  HOMA_ROOM: 'Sensors'
  HOMA_NAME: 'Solar PV'

  HASS_ENABLED: True
  HASS_DEVICE_ID: '' # use inverter id if empty
  HASS_DEVICE_NAME: 'Solar PV Balkonkraftwerk'
  HASS_NAME_PREFIX: 'Solar '
  HASS_AREA: 'Energie'
